logging:
  config: classpath:logback-spring.xml

spring:

  #freemarker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  redis:
    host: 134.175.130.172
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 1
    password: lwh@13660161032




gid:
  key: gid
  step: 1000